// Code generated by "generr"; DO NOT EDIT.
package fm5

import "fmt"

func IsTypeNotFoundWithGivenName(err error) (bool, string) {
	var name string
	if e, ok := err.(typeNotFoundWithGivenName); ok {
		name = e.TypeNotFoundWithGivenName()
		return true, name
	}
	return false, name
}

type TypeNotFoundWithGivenName struct {
	Name string
}

func (e *TypeNotFoundWithGivenName) TypeNotFoundWithGivenName() string {
	return e.Name
}
func (e *TypeNotFoundWithGivenName) Error() string {
	return fmt.Sprintf("typeNotFoundWithGivenName Name: %v", e.Name)
}
