// Code generated by "generr"; DO NOT EDIT.
package fmgo

import "fmt"

func IsTypeNotFoundWithGivenName(err error) bool {
	if _, ok := err.(typeNotFoundWithGivenName); ok {
		return true
	}
	return false
}

type TypeNotFoundWithGivenName struct {
}

func (e *TypeNotFoundWithGivenName) TypeNotFoundWithGivenName() {
	return
}
func (e *TypeNotFoundWithGivenName) Error() string {
	return fmt.Sprint("typeNotFoundWithGivenName")
}
