// Code generated by "fmgo"; DO NOT EDIT.
package e2e

func NewStructure(id int, name string) Interface {
	return &Structure{id: id, name: name}
}

type StructureOption func(*Structure)

func NewStructureOptions(opts ...StructureOption) Interface {
	i := &Structure{}
	for _, o := range opts {
		o(i)
	}
	return i
}
func WithId(id int) StructureOption {
	return func(i *Structure) {
		i.id = id
	}
}
func WithName(name string) StructureOption {
	return func(i *Structure) {
		i.name = name
	}
}
